### ISSUE TITLE
pipx error while loading shared libraries: libpython3.11.so.1.0

### ISSUE THREAD

**Issue by atomraymaker** [pkgxdev/pkgx#1006]
pipx seems to have lost a python context somewhere

Using Ubuntu 24.04

Steps to reproduce:

pkgx install pipx
pipx install pycowsay
pycowsay moo

Error:

~/.local/share/pipx/venvs/pycowsay/bin/python: error while loading shared libraries: libpython3.11.so.1.0: cannot open shared object file: No such file or directory

The pycowsay install does pickup the pkgx python at ~/.local/share/pipx/venvs/pycowsay/bin

python3.11 -> ~/.pkgx/python.org/v3.11.9/bin/python3.11

and there is a ibpython3.11.so.1.0 here:

~/.pkgx/python.org/v3.11.9/lib/libpython3.11.so.1.0

pkgx install python works.

**Comment by jhheider** [comment]
This is an interesting problem. On macOS, it works because it inherits the loader_path:
```
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 80
         name @loader_path/../../v3.11.8/lib/libpython3.11.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 3.11.0
compatibility version 3.11.0
```

does `pkgx pipx run pycowsay` work? it's makes sense that the package manager (pkgx) running a package manager (pipx) which installs a shim (~/.local/bin/pycowsay) might lose the surrounding environment needed. I wonder if there's a way to solve it without altering pipx internals to change the shim it creates.

**Comment by atomraymaker** [comment]
yeah, this does work. It is what chatgpt said also. Should pkgx set this up somehow with the pkgx install pipx? I worry that this isn't a global setting so adding it as a global env var could be an issue e.g the python in question is a depedency of pipx through pkgx and not accessible globally.

**Comment by atomraymaker** [comment]
pkgx pipx run pycowsay does also work. 

I did try setting the python location when installing things with pipx using PIPX_DEFAULT_PYTHON. Even doing pkgx install python and using that as a ref, but it got a similar error.

**Comment by jhheider** [comment]
That's exactly the problem. One solution is adding `pycowsay` to `projects/pypa.github.io/pipx/provider.yml` in the pantry, which lets us do:

```
$ pkgx pycowsay moo

  ---
< moo >
  ---
   \   ^__^
    \  (oo)\_______
       (__)\       )\/\
           ||----w |
           ||     ||
```

the other would be to just package `pycowsay` into the pantry, so it could be installed like any other pip venv, a la https://github.com/pkgxdev/pantry/blob/main/projects/aws.amazon.com/cli/package.yml.

**Comment by atomraymaker** [comment]
hmm, yeah, this is a few levels too deep of package managers. I will look at options without pipx. Thanks!

**Comment by mittalyashu** [comment]
@jhheider Running `pkgx pipx run pycowsay` did not resolved the issue.
