### ISSUE TITLE
warn: parse failure: valkey.io

### ISSUE THREAD

**Issue by alonronin** [pkgxdev/pkgx#1014]
i have this error when running pkgx commands on the terminal.  (pkgx 1.1.6 on macox sonoma 14.5)

for example:

```sh
$ node -v
```

then i run it with `x` command i get:

```sh
env +node && node -v 
warn: parse failure: valkey.io
v22.3.0 
```

<img width="1122" alt="Screenshot 2024-06-23 at 17 11 10" src="https://github.com/pkgxdev/pkgx/assets/846044/798290c8-afa2-4a64-a8a5-b131a49f7419">

it doesn't happen if i run `pkgx node -v` however if i install node with pkgx it happens every time i run node commands.

**Comment by jhheider** [comment]
Usually this is a minor file corruption in your local pantry. If so, `pkgx --sync` should fix it.

**Comment by alonronin** [comment]
> Usually this is a minor file corruption in your local pantry. If so, `pkgx --sync` should fix it.

solve it! thanx. great bot, btw!
