### ISSUE TITLE
Are you sure macOS x86-64 binaries in GitHub releases are x86-64?

### ISSUE THREAD

**Issue by felipecrs** [pkgxdev/pkgx#1019]
I forked pkgx (the cli) so that I can provide [my own pkgx binaries](https://github.com/felipecrs/pkgx/releases) with some fixes/improvements I need.

When doing so, I also refactored `cd.yaml` to not rely on self-hosted ARM64 runners.

I am mentioning this for two reasons:

1. Maybe you guys want to reuse the same idea to drop the dependency on self-hosted runners as well:

- https://github.com/felipecrs/pkgx/blob/4ba6b22c67bac8e12ca1a90c5e7ca7ae375e5181/.github/workflows/cd.yml
- https://github.com/felipecrs/pkgx/blob/4ba6b22c67bac8e12ca1a90c5e7ca7ae375e5181/scripts/build-binaries.sh

Note that the scripts are as ugly as possible, my only intention was to get it done however I could ASAP.

2. See this section:

https://github.com/pkgxdev/pkgx/blob/ba219daa68404f4dc6206ffce43f37d5ca25386f/.github/workflows/cd.yml#L61-L62

There's a problem. `macos-latest` is currently M1 (ARM64). I am wondering if the binary in the GitHub release is in fact a ARM64 binary named as if it was x86-64.

**Comment by felipecrs** [comment]
Oh, probably not (answering question 2). The latest pkgx release is from January, and I believe GitHub changed this after that.

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-private-repositories

**Comment by felipecrs** [comment]
Oh, another note:

- I have absolutely no intention to keep maintaining such pkgx fork. I created it solely for my own needs. I hope the fixes gets merged in the main repo and I can get rid of my fork.

**Comment by felipecrs** [comment]
@dosubot you went far this time 🤣🤣🤣

**Comment by mxcl** [comment]
@jhheider I believe the `os:` key is not relevant here right?

On the topic of making your own binaries for `pkgx` to consume, we'd like a flexible way to support that at some point for sure.

**Comment by jhheider** [comment]
This was because GitHub changed the macros-latest runners to arm64. Was addressed in brewkit.

**Comment by mxcl** [comment]
Should be ok now. If it wasn’t x64 then pantry builds would be failing.
