### ISSUE TITLE
`pkgx --sync` on `main` never finishes if the pantry repo was not updated in the last 24 hours

### ISSUE THREAD

**Issue by felipecrs** [pkgxdev/pkgx#1021]
I have a lot of pipelines stuck at `pkgx install`. After some troubleshooting, it seems that they aren't being able to sync the pantry.

Then I tried in my local machine and can reproduce it:

```console
pkgx --sync
```

Never finishes, hangs forever.

**Comment by felipecrs** [comment]
lol. Found out the issue!

Since there was no change in the last 24 hours of pantry git, the following line always returns true, causing an infinite loop!

https://github.com/pkgxdev/libpkgx/blob/2aec73a0c16222d2c1a4eddb96acc867dddaa191/src/hooks/usePantry.ts#L267

**Comment by felipecrs** [comment]
- https://github.com/pkgxdev/libpkgx/pull/73

**Comment by felipecrs** [comment]
@jhheider I realized this issue only affects/affected the main branch of pkgx, and not the last released version 1.1.6.

I'm very sorry about it.

**Comment by felipecrs** [comment]
In fact, let me keep it open just as a reminder that this has to be fixed before releasing a new version from main.

**Comment by jhheider** [comment]
That's great to know, and explains the lack of outrage. ;)

But it'll definitely need fixing.
