### ISSUE TITLE
x509 certificate trust error in pkgx docker container

### ISSUE THREAD

**Issue by bdruth** [pkgxdev/pkgx#1026]
Might be similar/related to https://github.com/pkgxdev/pkgx/issues/146

1. use pkgxdev/pkgx container image
2. `pkgx +tofu^1.7.1 tofu init`

Expected: `tofu init` works and is able to access resources at https://registry.opentofu.org

Actual: x509 cert error
```
╷
│ Error: Failed to resolve provider packages
│ 
│ Could not resolve provider hashicorp/http: could not connect to
│ registry.opentofu.org: failed to request discovery document: Get
│ "https://registry.opentofu.org/.well-known/terraform.json": tls: failed to
│ verify certificate: x509: certificate signed by unknown authority
╵
```
I'm guessing its a letsencrypt certificate?
<img width="211" alt="image" src="https://github.com/user-attachments/assets/8bc17d5a-2e4a-4cd9-89a4-96b31660a731">

Doing a `curl` from the docker host machine works, no SSL/TLS errors.

**Comment by jhheider** [comment]
Hm.
```shell
$ docker run -it --rm pkgxdev/pkgx
pkgx $ pkgx +tofu^1.7.1 tofu init
 ✓  ~/.pkgx/gnu.org/mpc/v1.3.1
 ✓  ~/.pkgx/gnu.org/gmp/v6.3.0
 ✓  ~/.pkgx/gnu.org/mpfr/v4.2.1
 ✓  ~/.pkgx/opentofu.org/v1.7.3
 ✓  ~/.pkgx/gnu.org/gcc/libstdcxx/v14.1.0
 ✓  ~/.pkgx/gnu.org/binutils/v2.42.0
OpenTofu initialized in an empty directory!

The directory has no OpenTofu configuration files. You may begin working
with OpenTofu immediately by creating OpenTofu configuration files.
pkgx $ touch main.tf
pkgx $ pkgx +tofu^1.7.1 tofu init

Initializing the backend...

Initializing provider plugins...

OpenTofu has been successfully initialized!

You may now begin working with OpenTofu. Try running "tofu plan" to see
any changes that are required for your infrastructure. All OpenTofu commands
should now work.

If you ever set or change modules or backend configuration for OpenTofu,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

that works for me out of the box. if you change your invocation to `pkgx +tofu^1.7.1 +curl.se/ca-certs tofu init` does it work? if so, the fix is as simple as adding a dependency on ca-certs.

**Comment by bdruth** [comment]
I'll try that - it might need to actually have something to do (i.e. not an empty directory) for it to hit a request that fails.

**Comment by bdruth** [comment]
adding the `ca-certs` explicitly worked, thank you!

should that be necessary?

**Comment by jhheider** [comment]
i'll add it to the package.yml so it's automatically handled.
