### ISSUE TITLE
unexpected error error sending request...invalid peer certificate: UnknownIssuer

### ISSUE THREAD

**Issue by alonronin** [pkgxdev/pkgx#1027]
hi i'm getting this error when trying to use pkgx.

× unexpected error error sending request for url (https://github.com/pkgxdev/pantry/archive/refs/heads/main.tar.gz): error trying to connect: invalid peer certificate: UnknownIssuer

<img width="801" alt="image" src="https://github.com/user-attachments/assets/38f9a898-a373-4efe-bd45-3a9c04691371">

**Comment by jhheider** [comment]
that's very strange. that's an SSL error trying to reach github. is it still happening? their SSL cert was issued in March, and I don't see any incident history. if you're still having this problem, what does:

```shell
curl -I https://github.com/pkgxdev/pantry/archive/refs/heads/main.tar.gz
```

show?

**Comment by alonronin** [comment]
I replaced computer and it worked. Strange behavior.
