### ISSUE TITLE
parse issue databricks.com

### ISSUE THREAD

**Issue by trentlarson** [pkgxdev/pkgx#1028]
Every time I try "x" or "pkgx" I get the following:

```
$ pkgx +python sh
× parse error databricks.com
│ this is a serious issue. please report the bug
╰─➤ https://github.com/pkgxdev/pkgx/issues/new?title=parse+issue+databricks.com
```

* I see no "databricks" in any file names under ~/.pkgx

* I get that no matter what package I try to use (eg. nodejs.org, npmjs.com, python.org).

* I have a directory that somehow injects an environment (seen [here](https://github.com/trentlarson/endorser-ch)), where it prints `env +git-scm.org +nodejs.org` when I cd to it. I get the same error there, though luckily I can run node there.

* I believe I ran pkgx in the last couple weeks successfully. I can't imagine what changed.

**Comment by jhheider** [comment]
> 2\. **Force Pantry Sync**:
>     Run the following command to force a pantry sync, which can help resolve any inconsistencies in the pantry data:
>     ```shell
>     pkgx --sync
>     ```

dosubot is correct that this is the most common fix.

**Comment by trentlarson** [comment]
Yes, indeed! `pkgx --sync` fixed it. 🙇
