### ISSUE TITLE
strange behaviors with 1.2.0

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/pkgx#1036]
These are different:

CMAKE_INCLUDE_PATH doesn't seem to be being set: https://github.com/pkgxdev/pantry/actions/runs/10776133971/job/29882224768 (1 example; a fix for another was explicit paths: https://github.com/pkgxdev/pantry/pull/7236/files

LD_LIBRARY_PATH (and path, weirdly) don't seem to include runtime deps with brewkit test? maybe? or the output is strange from brewkit is strange: https://github.com/pkgxdev/pantry/actions/runs/10820659200/job/30021167540. This should show php.net in PATH (though it clearly works on the command), and LD_LIBRARY_PATH doesn't seem to include gnu.org/gcc/libstdcxx. weirdly, laravel (#!/usr/bin/env php) works fine, but `php artisan` and `./artisan`, same bang-path, have GLIBCXX errors.

note that the second appears to be the same issue you saw in CI/CD with nodejs.

**Comment by mxcl** [comment]
This is handled by libpkgx and here’s the diff:

https://github.com/pkgxdev/libpkgx/compare/v0.17.0...v0.19.0

Nothing jumps out and this stuff is handled by `useShellEnv.ts` which is unchanged. So I’m clueless for now.

**Comment by mxcl** [comment]
For completeness here’s the diff for `pkgx` itself: https://github.com/pkgxdev/pkgx/compare/v1.1.6...v1.2.0

**Comment by jhheider** [comment]
bug is here: https://github.com/pkgxdev/pkgx/commit/bebba71a0259d70b5c42e1d1e813c03c54efaf25

since `projects` now includes versions, `projects.has('cmake.org')` fails. should be an easy fix.
