### ISSUE TITLE
Unstable API 'Deno.run.clearEnv'. The `--unstable-process` flag must be provided.

### ISSUE THREAD

**Issue by clanghans** [pkgxdev/pkgx#1038]
I was just about to try out pkgx on my Linux/Ubuntu based machine running following commands result in the the error: 

`Unstable API 'Deno.run.clearEnv'. The `--unstable-process` flag must be provided.` 

Haven't found anything in the docs about this. 

Steps to reproduce: 
```sh
❯ echo $(uname)
Linux
❯ echo $(uname -m)
x86_64
❯ rm ~/.local/bin/pkgx
❯ curl -Ssf https://pkgx.sh/$(uname)/$(uname -m).tgz | tar xz -C ~/.local/bin
❯ pkgx install nvim
Unstable API 'Deno.run.clearEnv'. The `--unstable-process` flag must be provided.
```

Edit: forgot to mention the version used -> pkgx 1.2.0

**Comment by fabarea** [comment]
Same for me, same environment. 
I also experienced the same message / error on macOS FYI

**Comment by mxcl** [comment]
Hmm, not sure how our tests didn't notice this. Apologies, new build coming up.

**Comment by mxcl** [comment]
I cannot reproduce on macOS with `pkgx install nvim` is there another way I can repro (want to verify I fix this).

**Comment by mxcl** [comment]
Released https://github.com/pkgxdev/pkgx/releases/tag/v1.2.1

Upgrade available via the curl one-liner or other mechanisms

**Comment by clanghans** [comment]
Thanks

**Comment by fabarea** [comment]
How to upgrade? I wonder if something else might be broken.

```
curl -fsS https://pkgx.sh | sh

sh: line 1: syntax error near unexpected token `newline'
sh: line 1: `<!DOCTYPE html>'
```

Command taken from the [docs](https://docs.pkgx.sh/run-anywhere/terminals)

Shell: zsh
OS: macOS

**Comment by jhheider** [comment]
command worked for me just now. hm. that looks like you're getting HTML back. likely an error page from the CDN, if you don't have anything blocking you. You should be able to `curl -fsS https://pkgx.sh | pkgx bat` and see what you're getting.
