### ISSUE TITLE
[Package Request] fastfetch

### ISSUE THREAD

**Issue by osalbahr** [pkgxdev/pkgx#1048]
I'd like it if `pkgx` packaged `fastfetch` but unfortunately it is not packaged yet. The process isn't clear from looking at https://docs.pkgx.sh/pantry. Can someone package it or guide me through how to? Thx!

```console
% ./pkgx fastfetch 
× nothing provides: fastfetch
│ we haven’t pkgd this yet. can you?
╰─➤ https://docs.pkgx.sh/pantry
```

**Comment by osalbahr** [comment]
This might already be tracked by the following issue:

- https://github.com/pkgxdev/pantry/issues/7109

**Comment by jhheider** [comment]
this has been requested here: https://github.com/pkgxdev/pantry/issues/7109

it looks like we're missing a few dependencies. but they may be optional. if they're optional it shouldn't be hard, but if they're required, then they'd need to be packaged as well.

We do have `neofetch` and `hyfetch` packaged, which are similar.
