### ISSUE TITLE
Is there an option to exclude a package?

### ISSUE THREAD

**Issue by chmac** [pkgxdev/pkgx#1058]
In an old nodejs project, I automatically get `+yarnpkg.com` added, but I manually added `+classic.yarnpkg.com`. However, I end up with a conflict. I have both versions of yarn installed, and the latest is the one that gets run from `yarn`. Can I somehow exclude that package from being picked up by pkgx?

**Comment by jhheider** [comment]
You can do `env -yarnpkg.com` to remove it. As currently constituted:

https://github.com/pkgxdev/pkgx/blob/f28d9311eac07c0dd0b4c3900eab2420199b6604/src/utils/devenv.ts#L76-L86

`.yarnrc` brings in v1, and `yarn.lock and .yarnrc.yml` bring in berry.

**Comment by jhheider** [comment]
I don't believe you can do it in a spec file. Only manually, using the `env` shell function created by the `dev` instance.

**Comment by jhheider** [comment]
`PKGX_POWDER= pkgx node~12 --version` seems to work:
```shell
jacob@illithid foo % dev
env +nodejs.org@20.0.0
jacob@illithid foo % pkgx node~12 --version
× unexpected error cannot intersect: @20.0.0 && ^12
│ Error: cannot intersect: @20.0.0 && ^12
│     at Module.intersect (https://deno.land/x/libpkgx@v0.17.0/src/utils/semver.ts:384:30)
│     at condense (https://deno.land/x/libpkgx@v0.17.0/src/plumbing/hydrate.ts:95:33)
│     at hydrate (https://deno.land/x/libpkgx@v0.17.0/src/plumbing/hydrate.ts:13:15)
│     at file:///Users/builder/actions-runner/_work/pantry/pantry/builds/pkgx.sh-1.1.6/src/prefab/install.ts:10:60
│     at failsafe (file:///Users/builder/actions-runner/_work/pantry/pantry/builds/pkgx.sh-1.1.6/src/prefab/failsafe.ts:5:18)
│     at default (file:///Users/builder/actions-runner/_work/pantry/pantry/builds/pkgx.sh-1.1.6/src/prefab/install.ts:10:47)
│     at eventLoopTick (ext:core/01_core.js:182:7)
│     at async default (file:///Users/builder/actions-runner/_work/pantry/pantry/builds/pkgx.sh-1.1.6/src/modes/x.ts:30:18)
│     at async default (file:///Users/builder/actions-runner/_work/pantry/pantry/builds/pkgx.sh-1.1.6/src/app.ts:48:11)
│     at async file:///Users/builder/actions-runner/_work/pantry/pantry/builds/pkgx.sh-1.1.6/entrypoint.ts:59:3
╰─➤ https://github.com/pkgxdev/pkgx/issues/new
jacob@illithid foo % PKGX_POWDER= pkgx node~12 --version
v12.22.12
```
I assume there's a bunch of things that could go wrong, with mismatching libraries and what have you, but if it works, it might be a sufficient workaround. You could use a tool like `just` or `xc` or a shell script to wrap the invocation to make it easier, i.e.:
```shell
jacob@illithid foo % just node12 --version
v12.22.12
jacob@illithid foo % cat justfile
node12 +ARGS:
  @PKGX_POWDER= pkgx node~12 {{ARGS}}
```

**Comment by chmac** [comment]
@jhheider That's awesome, thanks a lot. You're absolutely right, ordering does fix the issue I'm facing. 🥳  Would be awesome if `-foo` worked in spec files also, but I'm totally satisfied with the workaround.

Thanks again for working on pkgx and for all the help you've given me, I really appreciate it. 🧡
