### ISSUE TITLE
Issue when installing both rubocop and yamllint

### ISSUE THREAD

**Issue by waliid** [pkgxdev/pkgx#1059]
Hi guys,

### Description

When I use `pkgx` to install both `rubocop` and `yamllint`, I encounter an issue with `rubocop` which stops working if `yamllint` is installed. 
Both packages work fine individually, but when both are downloaded, `rubocop` fails to function. It seems the issue is related to `~/.pkgx/sqlite.org` because when I delete this folder, `rubocop` starts working again without issues.

### Steps to reproduce:
1. Install rubocop using `pkgx +ruby rubocop -v`:
   ```bash
   pkgx +ruby rubocop -v
   ```
   prints: `rubocop 1.69.1`

2. Install yamllint using `pkgx yamllint -v`:
   ```bash
   pkgx yamllint -v
   ```
   prints: `yamllint 1.35.1`

3. Try running `rubocop` again using:
   ```bash
   pkgx +ruby rubocop -v
   ```
   prints
   ```
   'RubyGems' were not loaded.
   $HOME/.pkgx/rubocop.org/v1.69.1/gems/bin/rubocop:9:in `require': cannot load such file -- rubygems (LoadError)
       from $HOME/.pkgx/rubocop.org/v1.69.1/gems/bin/rubocop:9:in `<main>'
   ```

### Expected behavior:

`rubocop` should work even after installing `yamllint`.

### Actual behavior:
`rubocop` fails to load when `yamllint` is installed.

### Environment:
- `pkgx` version: 1.3.1
- `rubocop` version: 1.69.1
- `yamllint` version: 1.35.1
- OS: MacOS 15.0.1 (24A348) - Darwin Kernel Version 24.0.0

Any idea of how can I fix that?

**Comment by jhheider** [comment]
```shell
pkgx rubocop -v
pkgx yamllint -v
pkgx rubocop -v
```
works in 1.1.6, but not in 1.3.1. i can confirm that removing `sqlite.org` "fixes" `rubocop`. so, this _seems_ like it might have something to do with sqlite caching.
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'json' (~> 2.3) - did find: [json-2.1.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/Users/jacob/.pkgx/rubocop.org/v1.69.1', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	from /Users/jacob/.pkgx/rubocop.org/v1.69.1/gems/bin/rubocop:25:in `<main>'
```

**Comment by waliid** [comment]
I've tried again with `pkgx` **1.3.1** and not able to reproduce the issue. 
Did you change something on your side?

**Comment by jhheider** [comment]
I think a new version of `sqlite.org` released over the weekend (https://dist.pkgx.dev/?prefix=sqlite.org/darwin/aarch64/). I wonder if whatever the conflict was is resolved by it.

**Comment by waliid** [comment]
Thank you, so let's close this issue.
