### ISSUE TITLE
Make “where packages that install packages install their packages” configurable

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pkgx#616]
When I run `tea --magic=zsh --silent` I get some shell code and there's this section.

```
# add our shims to the PATH
TEA_PREFIX="${TEA_PREFIX:-$HOME/.tea}"
if [[ "$PATH" != *"$TEA_PREFIX/.local/bin"* ]]; then
  export PATH="$TEA_PREFIX/.local/bin:$PATH"
fi

# we configure eg. `npm i -g`, cargo, etc. to install here
if [[ "$PATH" != *"$HOME/.local/bin"* ]]; then
  export PATH="$HOME/.local/bin:$PATH"
fi
```

You check to see if TEA_PREFIX is set or you set it to HOME, but then in the second part you use HOME and not TEA_PREFIX. Is that intentional? I have a .local/bin in my TEA_PREFIX but not my HOME.

**Comment by mxcl** [comment]
Yes this is intentional. We configure tools like `npm` to `install` to `~/.local/bin`. `~/.local/bin` is somewhat widely considered a `bin` in the home directory path. Many tools pick it.

If you don’t want this then it is generally desired to make such things configurable.
