### ISSUE TITLE
panic:File exists (os error 17): symlink 'tea' -> '/Users/albin/.tea/.local/bin/rust-gdbgui

### ISSUE THREAD

**Issue by albinkc** [pkgxdev/pkgx#639]
Panicked when running one of the suggested commands immediately after install
MacOS 13.4.1
Macbook Pro 16 (M1 Pro)

Here are my rust installation details:

`rust  1.71.0 installed with rustup with all the default options.`

Note: I installed rust before teacli on purpose because teacli was causing issues with rust-analyzer in VSCode (unable to find rust-docs or something similar if my memory serves right) and there was no way to force using rustup version no matter how many times I uninstalled it on tea-gui. It would just come back because I had magic enabled. Could be a skill issue on my end.

Full Error:

   wget -qO- tea.xyz/white-paper | glow -
resolving package graph
installed: ~/.tea/tea.xyz/gx/cc/v0.1.7
tea: installed: ~/.tea/tea.xyz/gx/cc/v0.1.7
installed: ~/.tea/zlib.net/v1.2.13
installing 9% 9.72 MiB/s 5.88/66 MiB
installing 9% 10.0 MiB/s 6.17/66 MiB
installing 11% 10.8 MiB/s 6.94/66 MiB
tea: installed: ~/.tea/openssl.org/v1.1.1u
installed: ~/.tea/charm.sh/glow/v1.5.1
installed: ~/.tea/rust-lang.org/v1.71.0
tea: installed: ~/.tea/rust-lang.org/v1.71.0

panic: spilt tea. we’re sorry and we’ll fix it… but you have to report the bug!

    https://github.com/teaxyz/cli/issues/new?title=panic%3AFile+exists+(os+error+17)%3A+symlink+'tea'+-%3E+'%2FUsers%2Falbin%2F.tea%2F.local%2Fbin%2Frust-gdbgui'

----------------------------------------------------->> attachment begin
AlreadyExists: File exists (os error 17): symlink 'tea' -> '/Users/albin/.tea/.local/bin/rust-gdbgui'
    at async Object.symlink (ext:deno_fs/30_fs.js:502:3)
    at async Promise.all (index 1)
    at async link (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/9a9e9255/src/prefab/install.ts:273:5)
    at async Promise.all (index 2)
    at async default (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/9a9e9255/src/prefab/install.ts:63:27)
    at async default (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/9a9e9255/src/prefab/setup.ts:94:38)
    at async run (file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/9a9e9255/src/app.main.ts:43:63)
    at async file:///private/var/folders/y3/yr3bxsy95c3gfwwj61ytbp000000gq/T/9a9e9255/src/app.ts:23:5
<<------------------------------------------------------- attachment end

**Comment by albinkc** [comment]
I would like to add that the same command  `wget -qO- tea.xyz/white-paper | glow -` worked when I tried it a second time after using tea magic to run node `node --version`.

I know the two events are probably unrelated, but just stating the facts

**Comment by mxcl** [comment]
Won’t happen with v1. Will close at final release.

**Comment by mxcl** [comment]
Yeah this specific issue is fixed.

magic is also gone so we won't infuriate you by installing things you don't want.

Also we have a PR to use rust’s own builds instead of our own which will fix your remaining issue.

Let me know if I can be of further assistance.
