### ISSUE TITLE
panic:FORK BOMB KILL SWITCH ACTIVATED

### ISSUE THREAD

**Issue by chrisbbreuer** [pkgxdev/pkgx#662]
I am a little unsure what kind of logs to report here, but considering I came across this in my console, I figured I'd share.

Would love to be of more help and share additional context. (please note, v0.39.4 was used and `.stacks` is the `TEA_DESTDIR`) 

<img width="891" alt="image" src="https://github.com/teaxyz/cli/assets/6228425/b2c6406f-0478-4846-8c1f-98ac89b42a12">

**Comment by kevinmichaelchen** [comment]
I'm also seeing this as well for **`rage`**.

Here's what I ran
```
echo hello | rage --recipients-file ~/.ssh/id_ed25519.pub --armor
```

https://github.com/teaxyz/pantry/blob/main/projects/crates.io/rage/package.yml

**Comment by mxcl** [comment]
In general this sort of thing should happen a lot less (if at all) with v1. Will close when we have migrated everything.

**Comment by mxcl** [comment]
v1 is out
