### ISSUE TITLE
`tea self-upgrade`

### ISSUE THREAD

**Issue by felipecrs** [pkgxdev/pkgx#665]
It would be great to have a simple way to self-upgrade tea. I know I can `sh <(curl tea.xyz)`, but:

- I try to avoid running scripts from internet as much as possible
- I don't want tea to attempt to install or reinstall its magic, and having to remember a flag to avoid such is also cumbersome (it's already cumbersome having to remember the whole `sh <(curl tea.xyz)`)

Maybe as part of `tea --sync`? Maybe a new sub-command like `tea self-upgrade`? Homebrew upgrades itself as part of `brew upgrade` IIRC.

**Comment by jhheider** [comment]
`tea -S +tea.xyz` will do it.

**Comment by felipecrs** [comment]
Well, kinda... that's only for when you have `tea --magic` installed:

```console
❯ tea --version
tea 0.39.0

❯ tea tea --version
tea 0.39.4
```

I was thinking more like `chezmoi upgrade`, which performs an in-place upgrade of the binary:

```console
❯ tea chezmoi@2.33 upgrade
installed: ~/.tea/chezmoi.io/v2.33.6
chezmoi version v2.36.0, commit be6e90307f9b5c8fa5d356183418a16d7bba69bf, built at 2023-07-28T19:09:51Z, built by goreleaser

❯ tea chezmoi@2.33 --version
chezmoi version v2.36.0, commit be6e90307f9b5c8fa5d356183418a16d7bba69bf, built at 2023-07-28T19:09:51Z, built by goreleaser
```

**Comment by mxcl** [comment]
Certainly a mechanism for upgrading `/usr/local/bin` would be good. We can special case ourselves potentially.

**Comment by mxcl** [comment]
v1 final won't have this feature as there's just too much revlock with the pantry and our actions, I'll work on a rapid 1.1 release tho after.

**Comment by felipecrs** [comment]
No worries, this is not urgent at all.

**Comment by orpheuslummis** [comment]
Suggestion: Include instructions in the documentation in addition of the code implementation. Thanks :)

**Comment by mxcl** [comment]
> Suggestion: Include instructions in the documentation in addition of the code implementation

Sorry orpheus, I'm not sure what you refer to. We have instructions for this in our documentation.

**Comment by orpheuslummis** [comment]
> > Suggestion: Include instructions in the documentation in addition of the code implementation
> 
> Sorry orpheus, I'm not sure what you refer to. We have instructions for this in our documentation.

The only mention I could find is https://docs.pkgx.sh/appendix/faq#how-do-i-run-the-latest-version-of-pkgx which could be improved. (Currently I'm not able to find time to make a PR, sorry!)

**Comment by mxcl** [comment]
I understand what you are saying, but with the current structure of our docs the FAQ is the only logical place to put this information.

If you can suggest a better place or a better structure for the documentation that would be helpful.

**Comment by j1philli** [comment]
This is throwing me for a loop, I have different versions of pkgx in different directories. How is that even possible. What is the expected way to update?

**Comment by davdroman** [comment]
This is funnily the current outcome:

```sh
$ pkgx --version
pkgx 1.0.0

$ pkgx pkgx@latest --version
 ✓  ~/.pkgx/pkgx.sh/v1.0.1
pkgx 1.0.1

$ pkgx --version
pkgx 1.0.0
```

Probably just needs a bit of tweaking internally.

I think ideally `--sync` should also update `pkgx`, but maybe @mxcl has other plans.

**Comment by mxcl** [comment]
1.1 will have pkgx special case itself, prompting for `sudo` if necessary to do an inplace overwrite.

**Comment by mxcl** [comment]
> This is throwing me for a loop, I have different versions of pkgx in different directories. How is that even possible.

`pkgx` packages itself it is treated the same way as any other package, thus you can create environments or scripts that lock a specific version of pkgx ensuring robustness etc.

> What is the expected way to update?

Per our docs we expect you to use `brew update`. If you don't use brew then you are saying “I know what I am doing”. Thus you can update yourself, download the release from github, pkgx is a single binary download on purpose, just download the new version and replace the old version. Job done.

The docs also say `pkgx install pkgx@latest` will self-update, this is not yet implemented. I am sorry. I wanted it done for 1.0 but there was too much to do. Even though it may seem like we mostly do `pkgx` around here, we also are building out the entire tea protocol as well as the oss.app gui complement all our web properties, marketing for several product offerings etc.

Has there ever been a point-oh release that was 100% complete? I don't think so, so well, I am sorry, genuinely I know how frustrating this kind of thing can be but also: yeah there was always going to be some holes. IT looks like we are promising this feature and it isn't there which I hate, but I know all the things I hate about this 1.0 release and this isn't all the way up there. Anyway we've updated the docs a few times to clarify these sorts of things, hopefully we're getting closer to being good.

Anyway, should be fixed soon, probs next week. I started the branch already #790

**Comment by j1philli** [comment]
No need for apologies. I am coming from a positive place and wanting the barrier of entry to be super low for pkgx. Thanks for your help and hard work as I get acquainted

**Comment by mxcl** [comment]
I started doing `pkgx install pkgx@latest` but then I wasn’t sure how to handle `pkgx install pkgx` and other such invocations. So for how I have made it so the installer will update the installed pkgx (if required):

```sh
curl https://pkgx.sh | sh
```

**Comment by felipecrs** [comment]
Thank you, @mxcl. I think that's ok.

**Comment by j1philli** [comment]
Thanks!
