### ISSUE TITLE
tea picks up root environment in nested projects with different environment

### ISSUE THREAD

**Issue by jakobvase** [pkgxdev/pkgx#681]
I work on a project with a `tea.yaml` in the root (.git) folder, where a subfolder has another `tea.yaml` and uses another version of node. I swear it's not my fault.

Problem is tea picks up the root configuration and ignores the nested configuration, so I have to delete the root configuration, `cd subfolder`, and then readd the root configuration if I need to do something there.

**Comment by jhheider** [comment]
This is an interesting problem. If you start outside the tree and cd directly to the subconfig, does it parse correctly? My guess is that once it knows it's beneath a dev-env, it's not looking for a new file but only watching the original for changes.

**Comment by jakobvase** [comment]
It's curious. It ignores both if I skip straight to the subfolder.

Subfolder tea.yaml:
```
dependencies:
  nodejs.org: 16
  classic.yarnpkg.com: 1.22.19
```

Root folder (.git) tea.yaml:
```
dependencies:
  nodejs.org: 14
  classic.yarnpkg.com: 1.22.19
```

Some switching directories and the node version:
```
Jakobs-MacBook-Pro:outside jakob$ node --version
v20.5.0
Jakobs-MacBook-Pro:outside jakob$ cd root/subfolder/
Jakobs-MacBook-Pro:subfolder jakob$ node --version
v20.5.0
Jakobs-MacBook-Pro:subfolder jakob$ cd ..
Jakobs-MacBook-Pro:root jakob$ node --version
v14.21.3
Jakobs-MacBook-Pro:root jakob$ cd subfolder/
Jakobs-MacBook-Pro:subfolder jakob$ node --version
v14.21.3
Jakobs-MacBook-Pro:subfolder jakob$ cd ..
Jakobs-MacBook-Pro:root jakob$ cd ..
Jakobs-MacBook-Pro:outside jakob$ node --version
v20.5.0
Jakobs-MacBook-Pro:outside jakob$ cd root/subfolder/
Jakobs-MacBook-Pro:subfolder jakob$ node --version
v20.5.0
```

There are also `package.json` files in the folders, but the versions specified in the `engines` there match the ones in the `tea.yaml` files.

**Comment by mxcl** [comment]
is your tea/cli up-to-date? There was a related bug fixed recently.

I think what happens is the inner folder fails to resolve the env altogether since it cannot resolve node^16 and node^18 and no error is surfaced since it happens in the shell hook.

Probs we should consider each layer upwards to be “don't apply if we already resolved that dep” or something like that.

**Comment by jakobvase** [comment]
```
jakob$ tea --version
tea 0.39.5
```

**Comment by jakobvase** [comment]
Just tried removing the `--silent` and there's no output when I do the above directory changes.

**Comment by Drache93** [comment]
I had the same problem; which presented as the #683 issue.
I started in the folder (aka opened in VSCode), should have been Node 16, but was Node 20.
I went up a folder, which resulted n Node 18, then went back down to my folder, was still Node 18.

Found this issue here, and realised I had a `.node-version` with node 18 up a folder.
Not sure why it was ending up on Node 20 though, seems it wasn't picking anything up until after I changed folders.

**Comment by rawkode** [comment]
I would really love for this kind of workflow to work, having just tried to do it without thinking.

I work in a monorepo and I put a `tea.yaml` at the top level with some common tooling, but each individual project has its own `tea.yaml` and I'd like for all the common tools to be available as well as local project tools.

**Comment by mxcl** [comment]
This should work in v1 however as it stands you would have to enable each `dev` separately, which is not great IMO.

`dev` is now a separate tool so we can enhance it a lot more without considering this situation.

Will close at v1 final and open a new ticket linking this one where we can discuss how it will work, however: should work with v1-alpha. LMK

**Comment by jakobvase** [comment]
Just tested it on v1-alpha, and can confirm that it's better now. However, there are still some things that don't work:

File structure:
```
outside
  | root
    | tea.yaml
    | subfolder
      | tea.yaml
```

root tea.yaml:
```
dependencies:
  nodejs.org: 14
  classic.yarnpkg.com: 1.22.19
env:
  AWS_PROFILE: 'my-profile'
```

subfolder tea.yaml:
```
dependencies:
  nodejs.org: 16
```

Examples:

```
Jakobs-MacBook-Pro:outside jakob$ cd root/subfolder/
tea +nodejs.org^16
(tea) Jakobs-MacBook-Pro:subfolder jakob$ yarn --version
-bash: yarn: command not found
```

I expected tea to pick up both the node and yarn packages from the root yaml, and the node from the subfolder yaml. I guess it's a decision whether tea should consider dev environments upwards in the tree when entering a folder. I think I would actually prefer for tea _not_ to do that, as it would keep things simpler, but I'll leave that to you. Continuing:

```
(tea) Jakobs-MacBook-Pro:subfolder jakob$ cd ..
tea -nodejs.org^16
tea +git-scm.org +nodejs.org^14 +classic.yarnpkg.com@1.22.19
(tea) undefined
```

Here it works as I expected - removing the dependency from the subfolder and adding the dependencies of the root. For some reason it now writes `undefined` in my shell, but I opened another issue for that (https://github.com/teaxyz/cli/issues/712). Moving on.

```
(tea) Jakobs-MacBook-Pro:root jakob$ cd subfolder/
(tea) Jakobs-MacBook-Pro:subfolder jakob$ node --version
v14.21.3
```

When I move from the parent folder to the subfolder, the environment is not automatically reloaded, even though I've already run `dev` in there. So I have to run `dev` every time I enter that folder. I'm pretty certain this is a bug.

**Comment by mxcl** [comment]
I believe most of these issues will be fixed in alpha.3 bar the nested `dev` environments, which we haven't yet decided how to handle.

I believe you should have to activate each env (one for the root, one for the subfolder). And probably they *should* nest by default, but you should possibly be able to say “no!” to that.

Discussion weldome.

**Comment by jakobvase** [comment]
I'm on alpha.2 now, and my only remaining issue is that the environment is not reloaded when I move from parent folder to subfolder, so I have to open two shell tabs, one where I do `cd root` and one where I `cd root/subfolder`.

If I do
```
outside $ cd root/
tea +git-scm.org +nodejs.org^14 +classic.yarnpkg.com@1.22.19
(tea) root $ cd subfolder/
(tea) subfolder $ node --version
v14.21.3
(tea) subfolder $ dev
dev: environment already active
```

So I can't run `dev` either.

I'll open a discussion for the nested envs.

**Comment by mxcl** [comment]
Closing as the feature set has changed, however we *must* support nested envs so will start talking in the discussion.
