### ISSUE TITLE
`pkg init` fails

### ISSUE THREAD

**Issue by abitrolly** [pkgxdev/pkgx#692]
[README.md](https://github.com/teaxyz/pantry#contributing) says this should work.

```
$ git clone https://github.com/teaxyz/pantry
$ cd pantry
$ pkg init
```

But it doesn't.

```
$ pkg init
error: pantry not found: /workspace/gitlab-development-kit/projects
```

**Comment by abitrolly** [comment]
```
$ DEBUG=1 tea -E
{
  tea: "/home/gitpod/.tea/tea.xyz/v0.39.6/bin/tea",
  deno: "1.36.0",
  v8: "11.6.189.12",
  typescript: "5.1.6"
}
/workspace/gitlab-development-kit/pantry/tea.yaml
/workspace/gitlab-development-kit/.ruby-version
/workspace/gitlab-development-kit/package.json
/workspace/gitlab-development-kit/Gemfile
resolving package graph
error: {}
```

I can try removing files, but it is still unclear why the error happens, and if there is a right way :tm: to fix it.

**Comment by jhheider** [comment]
The right fix is that we shouldn't be erroring if we hit an unparsable file, but it seems like we are. Most likely Gemfile, since it's sequential.

**Comment by abitrolly** [comment]
Moved pantry checkout to the root.

```bash
$ DEBUG=1 tea -E
{
  tea: "/home/gitpod/.tea/tea.xyz/v0.39.6/bin/tea",
  deno: "1.36.0",
  v8: "11.6.189.12",
  typescript: "5.1.6"
}
/workspace/pantry/tea.yaml
resolving package graph
error: {}
```


The error still happens.
Stranger thing 1: pantry error reports sibling directory, which makes no sense.

```bash
$ tea pkg init
error: pantry not found: /workspace/gitlab-development-kit/projects
$ pwd
/workspace/pantry
```

Stranger thing 2: with `DEBUG=1` the error is silenced.
```
$ DEBUG=1 tea pkg init
{
  tea: "/home/gitpod/.tea/tea.xyz/v0.39.6/bin/tea",
  deno: "1.36.0",
  v8: "11.6.189.12",
  typescript: "5.1.6"
}
error: {}
```

**Comment by jhheider** [comment]
Well, that is peculiar. Have to see if there's more debugging feasible.

**Comment by abitrolly** [comment]
More debug output is definitely needed. After restarting the workspace, installing `tea` again and reentering `bash` I've got another error.

```
$ tea pkg init
error: TEA_PANTRY_PATH is not set
$ pwd
/workspace/pantry
```

**Comment by mxcl** [comment]
`TEA_PANTRY_PATH` is set by the developer environment of pantry. If it's failing to set you can just set it yourself `TEA_PANTRY_PATH=$PWD`

The issues detailed in this thread are all fixed by 1.0.0-alpha.1 which I hope to release next week.

**Comment by mxcl** [comment]
Won’t happen with v1 due to developer environments being explicit, so we won’t keep going down a tree unless you explicitly added it. Will close at v1 release.

**Comment by mxcl** [comment]
Like: hopefully won't happen. We don't fully understand the bug here, but I suspect it was due to environments persisting when they shouldn't.

**Comment by mxcl** [comment]
closing, reopen if it still exists in v1
