### ISSUE TITLE
TEA_DIR not working 1.0.0-alpha.4

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pkgx#742]
```
> tea --version
tea 1.0.0-alpha.4
> echo $TEA_DIR
/Users/james/bla
> tea stable-diffusion-webui
/Users/james/.tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v1.5.1/bin/stable-diffusion-webui...
```

It should be /Users/james/**bla**/github.com/AUTOMATIC1111/stable-diffusion-webui/v1.5.1/bin/stable-diffusion-webui.

**Comment by kevinmichaelchen** [comment]
here's what i'm seeing

```
$ tea --version

deprecated: TEA_PREFIX has been renamed TEA_DIR, migrate before v1.0.0+gold
tea 1.0.0-alpha.4
```

**Comment by mxcl** [comment]
yes this is because libtea needs an update, the next version of cli this will work

**Comment by magnusviri** [comment]
With the name change to pkgx, is it still called TEA_DIR?

**Comment by mxcl** [comment]
It is now `PKGX_DIR` and this functionality should work now. Let’s just say: if it doesn't then I have no idea how pantry builds are working! :D
