### ISSUE TITLE
Tea uninstall fails

### ISSUE THREAD

**Issue by dcvz** [pkgxdev/pkgx#752]
I'm able to successfully install packages via `tea uninstall xxx` but I am unable to uninstall them as the docs say.
I get the following error:
```bash
× nothing provides: uninstall
│ we haven’t pkgd this yet. can you?
╰─➤ https://docs.tea.xyz/pantry
```

**Comment by mxcl** [comment]
yes this is not yet implemented

**Comment by j1philli** [comment]
https://docs.pkgx.sh/using-pkgx/pkgx-install#pkgx-uninstall
documentation should be updated to reflect what is currently possible
