### ISSUE TITLE
parse issue xcfile.dev

### ISSUE THREAD

**Issue by RSivakov** [pkgxdev/pkgx#759]
Your magicians' program has asked you to report this 🫶

**Comment by RSivakov** [comment]
➜ tea install open-interpreter@latest            
× parse error xcfile.dev
│ this is a serious issue. please report the bug
╰─➤ https://github.com/teaxyz/cli/issues/new?title=parse+issue+xcfile.dev

is full log of this

**Comment by mxcl** [comment]
our bad, open interpreter did not have this name in its pkg metadata, I have fixed this now so you should have success (`pkgx --sync` first).

However this is not the error, I don’t quite know what is TBH.

I recommend deleting your pantry and then trying again. `rm -rf ~/.tea/tea.xyz/var/pantry`

**Comment by mxcl** [comment]
Closing as assumed fixed. Reopen if not. Thanks.
