### ISSUE TITLE
Docs site links to non-existent project after rename

### ISSUE THREAD

**Issue by spencergilbert** [pkgxdev/pkgx#765]
:wave: 

I took a look to see if I could submit a PR to fix this, but didn't find anything in repo that seemed like the cause.

It seems the GitHub link in the header of https://docs.pkgx.sh/ is pointing to https://github.com/pkgxsh/cli - I'm guessing it's automatically pulled from the domain name or similar?

**Comment by mxcl** [comment]
Thanks I updated this. Was indeed a gitbook setting, not in source control :/
