### ISSUE TITLE
dev not picking up comments in pyproject.toml

### ISSUE THREAD

**Issue by j1philli** [pkgxdev/pkgx#774]
After refreshing an environment, the pkgx comments nor python declaration in the file are enforcing the python version in the dev environment.
![CleanShot 2023-10-03 at 20 26 12@2x](https://github.com/pkgxdev/pkgx/assets/3744255/95c5213c-7b0f-4fae-a354-0b1a91cb9527)

![CleanShot 2023-10-03 at 20 24 45@2x](https://github.com/pkgxdev/pkgx/assets/3744255/8d3fcc0c-d251-4768-9120-0a61d110d1b6)

### Discussed in https://github.com/orgs/pkgxdev/discussions/768

<div type='discussions-op-text'>

<sup>Originally posted by **j1philli** October  2, 2023</sup>
HI!
Just switched from tea to pkgx and went to get dev setup.
![CleanShot 2023-10-02 at 22 31 46](https://github.com/pkgxdev/pkgx/assets/3744255/ba40d899-7bda-4981-9679-f65bb82891ac)
Because of issues with python 3.12 and my project I want to have it use 3.11.4 so I put it in the pyproject.toml
![CleanShot 2023-10-02 at 22 33 12](https://github.com/pkgxdev/pkgx/assets/3744255/39ce3f6d-5ff2-4771-8af5-4f7cc5293f77)
But alas I still have 3.12 in my dev environment
![CleanShot 2023-10-02 at 22 33 39](https://github.com/pkgxdev/pkgx/assets/3744255/decb3962-fe7d-4774-9be0-e1f210d23191)
Any guidance would be much appreciated!</div>

**Comment by mxcl** [comment]
did this use to work pre 1.0?

**Comment by mxcl** [comment]
k def not, will fix for 1.0.1

**Comment by j1philli** [comment]
`Who would normally make the python this version?`
Sorry not sure I understand the question, isn't pinning versions of software pretty common place?

`What should we do in such a case?`
Installing all versions would not work. I wouldn't try and pull the version from the dependency list pyproject.toml because of the issue you specified. I would just make the pkgx comments work so that the user is able to specify the version they need in environment. I think if there are no comments then installing latest version like it does now is good enough.

I am surprised that you can't just send a command while in dev to change the version of an installed dependency

**Comment by mxcl** [comment]
> Sorry not sure I understand the question, isn't pinning versions of software pretty common place?

who enforces the python version, who installs it? the python package manager itself? The user?

**Comment by j1philli** [comment]
> who enforces the python version, who installs it? the python package manager itself? The user?
The user most of the time, then there are python utilities that also manage its own, seperate versions in environments they create(I don't think pkgx needs to worry about the latter at all).
The user needs to have python on machine. This is what pkgx should handle similar to the way https://github.com/pyenv/pyenv where you can specify different versions to use.
Then there are python environment managers like https://github.com/python-poetry/poetry that will use the systems python to run and then it manages environments with different versions of python and python packages installed in the environments it creats. Again, I don't think pkgx should be worried about these.
This has only come up because the poetry python dependency in the [pantry](https://github.com/pkgxdev/pantry/blob/929758b3206343263b78300f6eafae91f084a5c6/projects/python-poetry.org/package.yml#L9) wasn't specific enough to not use 3.12, so I wanted to override it somehow. Once pkgx gets the latest pantry version I believe it will install the proper version in dev and everything will work.
Hope that builds context, I would still consider myself a novice so let me know if something isn't clear.

**Comment by michjnich** [comment]
Python person here - when it comes to the management of the version of python itself for a project, different tools may specify it in different ways in config, but all of them expect a matching version to be installed already for it to work. If there isn't a version that matches, it won't work. 

So, if you for example only have python 3.11.4 on your machine: 

* Specifying 3.11.4 will work
* Specifying 3.11 or ~3.11.x will or even ^3.x.y work and give you 3.11.4 (wouldn't do that last one though :) )
* Specifying 3.11.6 will not work becuase there's only one version that matches and it's not on your machine. 

Installation of different python versions is often (not always) handled via another tool (eg. asdf, pyenv etc.)

**Comment by mxcl** [comment]
Tests cannot confirm the first part of this bug report, a `pyproject.toml` that has:

```
# pyproject. toml
# ---
# pkgx:
#   python@3.10
# ---
```

Results in python 3.10. Can you provide a test case?

The second part is a feature request to load python versions from the TOML which will go into 1.1

**Comment by j1philli** [comment]
Not the results I am seeing. I have a pyproject.toml with only what you stated as comments. I enter the directory it is located which is brand new. I check the version of python and it is the latest 3.11.6 instead of the expected 3.10
![CleanShot 2023-10-19 at 20 25 29](https://github.com/pkgxdev/pkgx/assets/3744255/b061c388-35bb-4500-a2e7-267e078a2c1c)

**Comment by mxcl** [comment]
k figured it out, fix coming up thanks. This only effects YAML FM in pyproject.toml that was a string with a `pkgx:` prefix.
