### ISSUE TITLE
pkgx should look for Cargo.toml instead of cargo.toml

### ISSUE THREAD

**Issue by uasi** [pkgxdev/pkgx#776]
Cargo's default manifest file name is capitalized `Cargo.toml`. As pkgx look for lowercase `cargo.toml`, it fails to load `rust-lang.org` env in a typical Cargo project.

> <img width="418" alt="Screenshot 2023-10-05 8 36 37" src="https://github.com/pkgxdev/pkgx/assets/22321/da9d4de1-d3e4-42b9-9952-e7ca8c79a3e0">

https://github.com/pkgxdev/pkgx/blob/b408b083a57b58878f0c3be89006e880f5653ad1/src/utils/devenv.ts#L45C13-L48

**Comment by jhheider** [comment]
#justlinuxproblems ;)

yes, this is one of the perils of developing on a mac, which defaults to case-insensitive filesystems.

**Comment by uasi** [comment]
The screenshot was taken on a Mac with case-insensitive AFPS, so this doesn't seem to be justlinuxproblems 🤔

**Comment by jhheider** [comment]
interesting. i wouldn't have expected that.

**Comment by mxcl** [comment]
thanks for the report. easy fix

the string comparison is case-sensitive hence the bug. However, should we fix that too? Probs not. Just asking.

**Comment by svenjacobs** [comment]
Cloning the project I get the following error:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'fixtures/Cargo.toml'
  'fixtures/cargo.toml'
```

This is on macOS with APFS file system. Both files still exist in [fixtures](https://github.com/pkgxdev/pkgx/tree/main/fixtures).

**Comment by jhheider** [comment]
that should fix it. those little errors that git doesn't know how to handle can be messy.

**Comment by mxcl** [comment]
my bad, I have no idea how I achieved this error lol
