### ISSUE TITLE
bug: pkgx's git is slow

### ISSUE THREAD

**Issue by aslafy-z** [pkgxdev/pkgx#784]
While making my first steps with pkgx, I found that my shell became really slow at giving back the prompt.
Running `zsh -x` showed me that it was caused by Git. I was about to start a contribution for the pantry and just executed a `dev` command. I realized it installed the `git` package from pkgx and that my shell was not using the system Git, but the one from pkgx.

For example, `git branch` went from taking about ~3ms to **more than 1s**!

Here's a reproduction link: https://github.com/aslafy-z/pkgx-reproduce-slow-git

Do you have any idea where this issue might be coming from?

**Comment by jhheider** [comment]
`git` uses a shim to try and detect if it needs to load any git-* commands. You can read the shim [here](https://github.com/pkgxdev/pantry/blob/main/projects/git-scm.org/git-shim)

So, do you see the slowdown using `~/.pkgx/git-scm.org/v2/libexec/git ...`? That would tell us if it's the shim, or possibly something else. It's worth nothing that 500ms is something on the order of slowdown we see from `deno` startup when calling the `pkgx` binary, so it's possible there is an additional `pkgx` invocation (or two) in the thread resulting in a detectable delay.

You can also run the shim with `bash -x` to see what calls it's making: `bash -x ~/.pkgx/git-scm.org/v2/bin/git ...`.

**Comment by aslafy-z** [comment]
Yup, I tracked it down to the `~/.pkgx/git-scm.org/v2/libexec/git` binary

**Comment by jhheider** [comment]
Testing with `hyperfine` shows some but not as much variance as you're seeing:
```shell
$ pkgx hyperfine -w3 -m1000 "~/.pkgx/git-scm.org/v2/libexec/git --version"
Benchmark 1: ~/.pkgx/git-scm.org/v2/libexec/git --version
  Time (mean ± σ):       2.2 ms ±   0.1 ms    [User: 1.4 ms, System: 0.6 ms]
  Range (min … max):     2.0 ms …   3.3 ms    1000 runs

  Warning: Command took less than 5 ms to complete. Note that the results might be inaccurate because hyperfine can not calibrate the shell startup time much more precise than this limit. You can try to use the `-N`/`--shell=none` option to disable the shell completely.
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

$ pkgx hyperfine -w3 -m1000 "/usr/bin/git --version"
Benchmark 1: /usr/bin/git --version
  Time (mean ± σ):       4.2 ms ±   0.1 ms    [User: 1.9 ms, System: 1.3 ms]
  Range (min … max):     3.8 ms …   5.6 ms    1000 runs

  Warning: Command took less than 5 ms to complete. Note that the results might be inaccurate because hyperfine can not calibrate the shell startup time much more precise than this limit. You can try to use the `-N`/`--shell=none` option to disable the shell completely.
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
```

running it under a pantry checkout isn't much different:
```shell
$ pkgx hyperfine -w3 -m1000 "/usr/bin/git --version"
Benchmark 1: /usr/bin/git --version
  Time (mean ± σ):       4.3 ms ±   0.2 ms    [User: 2.0 ms, System: 1.4 ms]
  Range (min … max):     3.9 ms …   7.2 ms    1000 runs

  Warning: Command took less than 5 ms to complete. Note that the results might be inaccurate because hyperfine can not calibrate the shell startup time much more precise than this limit. You can try to use the `-N`/`--shell=none` option to disable the shell completely.
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

$ pkgx hyperfine -w3 -m1000 "~/.pkgx/git-scm.org/v2/libexec/git --version"
Benchmark 1: ~/.pkgx/git-scm.org/v2/libexec/git --version
  Time (mean ± σ):       2.3 ms ±   0.4 ms    [User: 1.4 ms, System: 0.7 ms]
  Range (min … max):     2.0 ms …   9.1 ms    1000 runs

  Warning: Command took less than 5 ms to complete. Note that the results might be inaccurate because hyperfine can not calibrate the shell startup time much more precise than this limit. You can try to use the `-N`/`--shell=none` option to disable the shell completely.
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
```

so, what platform and architecture are you running on? this was tested under darwin-aarch64.

**Comment by aslafy-z** [comment]
I can reproduce this within a linux-amd64 8vcpu codespace environment, within the repro repository linked in OP. Wait for it to initialize and run `bash bench.sh`.

**Comment by jhheider** [comment]
> FYI, I updated my initial answer. I can confirm the latencies comes from the shim, specifically the part that runs pkgx --provider.

That, unfortunately, sounds unavoidable, due to `pkgx` overhead. However, based on the shim, if there's no command (a la `git --version`) or a command that ships with `git`, then `pkgx` shouldn't get called. That's everything under `libexec`.

Looks like the buggy line is:
```shell
elif [ -x "$libexec/git-$_CMD" -a -f "$libexec/git-$cmd" ]
```
if it's fixed to
```shell
elif [ -x "$libexec/git-$cmd" -a -f "$libexec/git-$cmd" ]
```
then it works as expected. i'll make that change to our package. you can either make that change locally, or remove and re-install git-scm.org once it finishes building.

good catch.

**Comment by jhheider** [comment]
https://github.com/pkgxdev/pantry/actions/runs/6438659399

after this, it should only be slow when searching for external commands it doesn't ship.

**Comment by aslafy-z** [comment]
So, 500ms from `pkgx git` to the shim, and 500ms for the extra check with pkgx --provider.
Two pkgx startups for `git branch`, 500ms each. A single one for `git --version`.

Git is often used in shell prompts like it is in the default codespace setup. It is really slow to work with.

I've read in #341 the plan was to rewrite the cli in rust after the 1.0 release. Is it still something you want to do?

**Comment by jhheider** [comment]
we certainly need the oft-called bits to be the fast. that'll always be our goal.

**Comment by aslafy-z** [comment]
I stared at this weird $_CMD earlier and was a bit confused. I could have sworn it appeared in both conditions. Thanks for the quick solution @jhheider, it changes everything!

**Comment by jhheider** [comment]
what are friday nights for? ;)

**Comment by mxcl** [comment]
Thanks all.

`pkgx` needs to be way faster in general. We intend to make a cache for pantry reads which should reduce as much as deno makes possible. Eventually we would like to rewrite in rust, but I have too many TODO items before that.

The cache should make it so even this situation would have been fast, though I'm glad it wasn't since we caught the bug.

Need to use `set -u` more often I think.

**Comment by philipgiuliani** [comment]
Is it possible to disable pkgx's custom git? I'm having http://starship.rs in my shell which displays the git status and branch in the prompt. Usually its super fast, but when running `dev` my shell gets super slow and `starship --timings` shows that its because of the `git` commands.

**Comment by jhheider** [comment]
Hm.
```shell
$ pkgx hyperfine '/usr/bin/git status'
Benchmark 1: /usr/bin/git status
  Time (mean ± σ):      32.7 ms ±   2.1 ms    [User: 8.3 ms, System: 25.5 ms]
  Range (min … max):    30.2 ms …  38.8 ms    79 runs
 
$ pkgx hyperfine '~/.pkgx/git-scm.org/v2/bin/git status'
Benchmark 1: ~/.pkgx/git-scm.org/v2/bin/git status
  Time (mean ± σ):      35.3 ms ±   2.1 ms    [User: 9.8 ms, System: 25.6 ms]
  Range (min … max):    32.6 ms …  43.2 ms    77 runs
```

can you tell _which_ git command? if you have the current version of the shim, it should only be slower if it can't find the git command you're running:
```bash
#!/bin/sh

set -e

find_git_command() {
  for arg in "$@"; do
    case $arg in
    -*);;
    *)
      echo "$arg"
      return  # found the command!
    esac
  done
}

libexec="$(cd "$(dirname "$0")/.." && pwd)"/libexec

# extract the git subcommand
cmd=$(find_git_command "$@")

_provides() {
  if foo="$(pkgx --provider git-"$cmd")"; then
    echo "$foo"
  else
    # syncing is slow but let’s be sure about it
    pkgx --sync --provider git-"$cmd"
  fi
}

if [ -z "$cmd" ]; then
  exec "$libexec/git" "$@"
elif [ -x "$libexec/git-$cmd" ] && [ -f "$libexec/git-$cmd" ]; then
  exec "$libexec/git" "$@"
elif type "git-$cmd" >/dev/null 2>&1; then
  exec "$libexec/git" "$@"
elif command -v pkgx >/dev/null 2>&1 && pkg=$(_provides); then
  exec pkgx +"$pkg" "$libexec/git" "$@"
else
  exec "$libexec/git" "$@"
fi
```
if that doesn't match your shim _exactly_, you can `rm -rf ~/.pkgx/git-scm.org && pkgx +git-scm.org` to reinstall it. however:
```shell
$ pkgx hyperfine '~/.local/bin/git status'
Benchmark 1: ~/.local/bin/git status
  Time (mean ± σ):     616.7 ms ±   8.7 ms    [User: 376.4 ms, System: 106.8 ms]
  Range (min … max):   600.0 ms … 631.5 ms    10 runs
```
if you have _that_ shim installed, it basically always results in a pkgx invocation. so, a quick fix is to have git installed from your package manager and remove `~/.local/bin/git`, or alias/link/directly reference the `~/.pkgx/git-scm.org/v2/bin/git` shim.

**Comment by philipgiuliani** [comment]
You are right `git status` is actually fast! I've checked what `starship` is doing (by using STARSHIP_LOG=trace env variable) and found this command:
```
git -C . --no-optional-locks status --porcelain=2 --branch
```

I can confirm that this command takes 1.023s with `dev` and just 0.042s after `dev off`. Let me know if you can reproduce it.

**Comment by jhheider** [comment]
that's a good one. this is finding the command as `.`:
```bash
find_git_command() {
  for arg in "$@"; do
    case $arg in
    -*);;
    *)
      echo "$arg"
      return  # found the command!
    esac
  done
}
```
so, it's looking for a pkgx package called `git-.`. i think i can exclude that case.

this seems to work:
```bash
find_git_command() {
  for arg in "$@"; do
    if test "$SKIP" = 1; then
      SKIP=0
      continue
    fi
    case $arg in
    -C) SKIP=1; continue;;
    -*);;
    *)
      echo "$arg"
      return  # found the command!
    esac
  done
}
```
you can make that change directly to your `git` shim; i'll push it to the repository. after applying:
```shell
$ pkgx hyperfine '~/.pkgx/git-scm.org/v2/bin/git -C . --no-optional-locks status --porcelain=2 --branch'
Benchmark 1: ~/.pkgx/git-scm.org/v2/bin/git -C . --no-optional-locks status --porcelain=2 --branch
  Time (mean ± σ):      35.5 ms ±   3.5 ms    [User: 10.4 ms, System: 26.2 ms]
  Range (min … max):    31.0 ms …  53.5 ms    51 runs
```

**Comment by jhheider** [comment]
it's a very weird case. one of the few ways a non-flag argument can precede the command.

**Comment by philipgiuliani** [comment]
Amazing, thanks for the quick fix! 🥳

**Comment by jhheider** [comment]
thanks for providing in-depth troubleshooting. you made it easy to find the bug by narrowing down exactly which conditions triggered it.

**Comment by aslafy-z** [comment]
What about other global options that takes attributes like `-c` for eg.?

**Comment by jhheider** [comment]
Should definitely be handled.

**Comment by mxcl** [comment]
If you already have the latest version of `git` cached you will need to delete it to get the update, otherwise `pkgx +git@latest` will work. In a future bug fix release `git@latest` will work in all cases.

**Comment by fredrikaverpil** [comment]
I'm sorry, I didn't quite follow what the fix was here. I just installed brew, pkgx and starship on a brand new macbook pro today, and I get a delay when I hit enter in a git repo (which triggers a redraw of the starship prompt) as well as missing git status symbols in the prompt.

The output of `env STARSHIP_LOG=trace starship timings` shows the following:

```
[DEBUG] - (starship::modules::git_status): New repo status created
[TRACE] - (starship::context): Executing command "git" with args ["-C", "/Users/fredrik/code/dotfiles", "--no-optional-locks", "status", "--porcelain=2", "--branch"] from context
[TRACE] - (starship::utils): Creating Command for binary "git"
[TRACE] - (starship::utils): Using "/Users/fredrik/.pkgx/git-scm.org/v2.42.1/bin/git" as "git"
[DEBUG] - (starship::modules::git_status): get_repo_status: git status execution failed
[TRACE] - (starship::modules): Took 516.221667ms to compute module "git_status"
[TRACE] - (starship::config): No config found for "git_status": Option "git_status" not found
```

If I run `env -git-scm.org` in the git repo and hit enter, there is no longer a delay in redrawing the prompt.

<img width="432" alt="image" src="https://github.com/pkgxdev/pkgx/assets/994357/4abdc2e5-9be0-453e-8d74-63490379b22d">

**Comment by jhheider** [comment]
max is saying, once `pkgx` downloads git-scm.org for a specific version, it doesn't re-download it, unless it's missing (or it needs a different version).

to get the fixes i've added, you can `pkgx +git+latest` (forces a re-download), or `rm -rf ~/.pkgx/git-scm.org` (removes all cached binaries; subsequent calls to the shim at ~/.local/bin/git, if `pkgx install git`ed, will download the updated bottle.)

**Comment by fredrikaverpil** [comment]
@jhheider I just tried what you mentioned (`rm -rf ~/.pkgx/git-scm.org` which forced a re-download after re-entering the git project directory), but I still see the delay/failed git status problem. I now have git-scm v2.42.1.

Thing is you added the fix a couple of days ago, and I installed pkgx and hit `dev` in this project _today_ and I still see this issue. Do you think I'm doing something wrong on my end?

**Comment by jhheider** [comment]
hm. strangely, if i download git fresh, it has the old shim, not the new one. you can easily fix yours by replacing ~/.pkgx/git-scm.org/v2/bin/git with https://github.com/pkgxdev/pantry/tree/main/projects/git-scm.org/git-shim. let me see why it's not built into the new one.

**Comment by jhheider** [comment]
it's possible CI didn't trigger the build, since I didn't change the package.yml. sloppy on my part, if so. i'll trigger a rebuild now.

**Comment by fredrikaverpil** [comment]
Awesome, the rebuilt [GHA workflow](https://github.com/pkgxdev/pantry/actions/runs/6910113814) did the trick!

Thanks @jhheider!

**Comment by jhheider** [comment]
[this](https://github.com/pkgxdev/pantry/actions/runs/6910113814) rebuild got it. interestingly, @mxcl, `pkgx +git@latest` didn't seem to do it, but `rm -rf ...` did.

**Comment by jhheider** [comment]
you beat me to it, @fredrikaverpil . glad to be of assistance.

**Comment by fredrikaverpil** [comment]
@jhheider I'm actually having similar issues with https://github.com/sindrets/diffview.nvim, where git becomes slow and I wish I could just not have `git-scm.org` loaded by default in my projects.

Is there any way to globally configure pkgx never to use `git-scm.org`?

**Comment by fredrikaverpil** [comment]
Seems like it's [this line](https://github.com/pkgxdev/pantry/blob/fc48863ecfc64a7d5741cb0e6665a1b414c474f7/projects/git-scm.org/git-shim#L31) that causes the delay. I added some debug printing:

```bash
#!/bin/sh

set -e

find_git_command() {
  for arg in "$@"; do
    if test "$SKIP" = 1; then
      SKIP=0
      continue
    fi
    case $arg in
    -C) SKIP=1; continue;;
    -*);;
    *)
      echo "$arg"
      return  # found the command!
    esac
  done
}

libexec="$(cd "$(dirname "$0")/.." && pwd)"/libexec

# extract the git subcommand
cmd=$(find_git_command "$@")

# echo $cmd into log file /tmp/gitlog.log
echo "cmd: $cmd" >> /Users/fredrik/code/dotfiles/gitlog.log

_provides() {
  if foo="$(pkgx --provider git-"$cmd")"; then
    echo "_provides returns: $foo" >> /Users/fredrik/code/dotfiles/gitlog.log
    echo "$foo"
  else
    echo "_provides goes into else clause for cmd: $cmd" >> /Users/fredrik/code/dotfiles/gitlog.log
    # syncing is slow but let’s be sure about it
    pkgx --sync --provider git-"$cmd"
  fi
}

if [ -z "$cmd" ]; then
  exec "$libexec/git" "$@"
elif [ -x "$libexec/git-$cmd" ] && [ -f "$libexec/git-$cmd" ]; then
  exec "$libexec/git" "$@"
elif type "git-$cmd" >/dev/null 2>&1; then
  exec "$libexec/git" "$@"
elif command -v pkgx >/dev/null 2>&1 && pkg=$(_provides); then
  exec pkgx +"$pkg" "$libexec/git" "$@"
else
  exec "$libexec/git" "$@"
fi
```

And this was the resulting log file:

```
cmd: status
cmd: rev-parse
cmd: ls-files
cmd: version
cmd: rev-parse
cmd: rev-parse
cmd: log
cmd: gc.auto=0
_provides goes into else clause for cmd: gc.auto=0
cmd: submodule.recurse=false
_provides goes into else clause for cmd: submodule.recurse=false
cmd: show
cmd: submodule.recurse=false
_provides goes into else clause for cmd: submodule.recurse=false
cmd: show
cmd: status
```

Does this help to figure out what's going on?

**Comment by mxcl** [comment]
> [this](https://github.com/pkgxdev/pantry/actions/runs/6910113814) rebuild got it. interestingly, @mxcl, `pkgx +git@latest` didn't seem to do it, but `rm -rf ...` did.

yeah I need to make `git@latest` check for an updated tarball, currently it does not.

**Comment by mxcl** [comment]
> Is there any way to globally configure pkgx never to use git-scm.org?

This has been requested before. I'm not yet sure how to handle the configuration. We add git so the user doesn’t need the Xcode Command Line Tools to dev which is a feature, though in cases where the user doesn't want that it is reasonable we allow such opt outs.

**Comment by fredrikaverpil** [comment]
@jhheider I opened a PR here: https://github.com/pkgxdev/pantry/pull/4121

This is quite brittle, as it's just a matter of time before git adds arguments which will require a change here. I would personally like to disable `git-scm.org` globally for when using `dev` because of this, like I mentioned above.
