### ISSUE TITLE
`tea uninstall tea` fails

### ISSUE THREAD

**Issue by permezel** [pkgxdev/pkgx#788]
Per the FAQ in the docs: `tea uninstall tea` will uninstall.

```
% tea uninstall tea 
tea: command not found: uninstall
```

```
% tea --version
tea 0.39.6
```

```
% tea --sync    
pantries sync’d ⎷
tea: empty pkg env
% tea uninstall    
tea: command not found: uninstall
```

**Comment by mxcl** [comment]
Dupes #752

**Comment by mxcl** [comment]
If you are trying to uninstall `tea` then `rm -rf ~/.tea` and remove the tea binary if placed elsewhere. For `pkgx` it is the same just `~/.pkgx`
