### ISSUE TITLE
Running `dev` in Node projects should add the package manager according to the lockfile

### ISSUE THREAD

**Issue by noClaps** [pkgxdev/pkgx#789]
For instance, if a `bun.lockb` file is present, Bun should be added, or if `yarn.lock` is present then Yarn should be added, etc.

The default can be npm, if no lockfile is present.

**Comment by mxcl** [comment]
we handle yarn for the presence of `.yarnrc` but not for the lock file. Easy add. Any other files we should spot?

**Comment by noClaps** [comment]
There's also PNPM with their `pnpm-lock.yaml`.

**Comment by mxcl** [comment]
@noClaps will add thanks.

**Comment by mxcl** [comment]
will be in 1.1 which I hope to release early next week
