### ISSUE TITLE
Missing Node Versions in Repo?

### ISSUE THREAD

**Issue by yoroshikun** [pkgxdev/pkgx#798]
First of all thanks for releasing this, I am trying to integrate this with my team however we are getting stuck with specific projects using a specific node version. 

### Example
`pkgx +node@18.17.1 node -v` *Error* cannot resolve version
```
resolving graph…× version unavailable nodejs.org@18.17.1
│ please check the following url for available versions
╰─➤ https://dist.pkgx.dev/?prefix=nodejs.org
```
`pkgx +node@18.17.0 node -v`
```
Node 18.17.0
```

### Solution
Is there any reason why some node versions are skipped, can we build them ourselves?

**Comment by mxcl** [comment]
We got it now https://dist.pkgx.dev/?prefix=nodejs.org/darwin/aarch64/

I'll review where we describe how to report missing versions and supplement it.

Like Jacob says we packaged the latest version of all minors for tools like node *mostly*, but haven't got to the point where we have absolutely everything yet. Happy to do builds when requested though. Let us know if you need more.
