### ISSUE TITLE
Determine npm version using package.json, "engines" 

### ISSUE THREAD

**Issue by yoroshikun** [pkgxdev/pkgx#803]
I was wondering if there is a way for the "dev" script to automatically extract the expected npm version from the "engines" key in the package.json file.

### Current
```
  "engines": {
    "node": "^18.17.0",
    "npm": "^9.6.7"
  },
```
node -v > (finds .node_version) -> v18.17.1
npm --version > (default for node version) v10.2.0

### Expected 

node -v > (finds .node_version) -> v18.17.1
npm --version > (latest above restriction or exact) -> v9.6.7 

Thanks for the hard work in advance~

**Comment by mxcl** [comment]
we totally can do this. It's not too hard. I'll try to get to it this week, but if you are interested it should be a fairly simple modification to: https://github.com/pkgxdev/pkgx/blob/main/src/utils/devenv.ts#L156-L161

**Comment by jhheider** [comment]
> might be more work for a new contributor to review and that

we've got plenty to do, so we always welcome the opportunity to turn a new contributor into a seasoned contributor. 💪
