### ISSUE TITLE
can not overwrite dependencies of pkgx packages even if the new one is acceptable

### ISSUE THREAD

**Issue by j1philli** [pkgxdev/pkgx#806]
![CleanShot 2023-10-12 at 22 06 48](https://github.com/pkgxdev/pkgx/assets/3744255/463092f7-385c-436e-9e90-bc668633e41b)
this way I am trying to remove the first version but it won't remove because it is a dep of another pkgx package
![CleanShot 2023-10-12 at 22 12 32](https://github.com/pkgxdev/pkgx/assets/3744255/0a151bb5-fa50-4229-a61f-ab45c77e5beb)
pkgx.yaml won't over ride what gets installed even though it is in the accepted range
![CleanShot 2023-10-12 at 22 07 44](https://github.com/pkgxdev/pkgx/assets/3744255/8e24d5bc-af79-44bd-81ab-d16f36834f2f)

**Comment by mxcl** [comment]
I'm confused, is your report:

* `env -python.org` doesn’t work
* that you are expecting a different python version to 3.11.x—if so, which?

**Comment by j1philli** [comment]
Both. As the title suggests, pkgx packages that are dependencies of other pkgx packages can not be changed even if they fall into accepted version range.
Python is a dependency of poetry so pkgx install python for us, it installs the latest. However I need it to a different version.
I try to specify in pkgx.yaml but it does not change to that version even though it is in the allowed version for poetry.
I also try to ```env -python.org``` so that I can remove the current version to install the one I need but it does not work for packages that are dependencies.

**Comment by jhheider** [comment]
Try this:
```shell
$ dev
 × no env
$ env +python-poetry.org
 ✓  ~/.pkgx/python-poetry.org/v1.6.1
$ python --version
Python 3.11.6
$ env +python~3.10
python --version
Python 3.10.13
```

**Comment by j1philli** [comment]
Interesting.
So I needed 3.11.0 so running ```env +python@3.11.0``` overwrote 3.11.6 as you suggested! Thanks! It does not save this though, so exiting and coming back to the dev environment has 3.11.6 again.
Doing as you say for downgrading minor version results in:
```
env +python~3.10
resolving graph…× unexpected error cannot intersect: ~3.11 && ~3.10
│ Error: cannot intersect: ~3.11 && ~3.10
│     at Module.intersect (https://deno.land/x/libpkgx@v0.14.1/src/utils/semver.ts:382:30)
│     at condense (https://deno.land/x/libpkgx@v0.14.1/src/plumbing/hydrate.ts:78:33)
│     at hydrate (https://deno.land/x/libpkgx@v0.14.1/src/plumbing/hydrate.ts:13:15)
│     at file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/prefab/install.ts:9:58
│     at failsafe (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/prefab/failsafe.ts:5:18)
│     at default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/prefab/install.ts:9:45)
│     at eventLoopTick (ext:core/01_core.js:183:11)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/modes/internal.use.ts:16:20)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/app.ts:57:20)
│     at async file:///Users/builder/actions-runner/_work/pkgx/pkgx/entrypoint.ts:59:3
╰─➤ https://github.com/pkgxdev/pkgx/issues/new

**Comment by jhheider** [comment]
Is that after adding python=3.11.0? I wouldn't expect it to work then.

**Comment by jhheider** [comment]
Ah, well, that would be the conflict then. Note that the operators are slightly different. I believe we treat `@` as `~`, as that's the most likely expectation:
```shell
$ pkgx +python@3.11 python --version
Python 3.11.6
$ pkgx +python~3.11 python --version
Python 3.11.6
$ pkgx +python@3.11.0 python --version
 ✓  ~/.pkgx/python.org/v3.11.0
Python 3.11.0
$ pkgx +python^3.11 python --version
Python 3.12.0
```

**Comment by j1philli** [comment]
Ahh interesting. Thanks

**Comment by j1philli** [comment]
> Try this:
> 
> ```shell
> $ dev
>  × no env
> $ env +python-poetry.org
>  ✓  ~/.pkgx/python-poetry.org/v1.6.1
> $ python --version
> Python 3.11.6
> $ env +python~3.10
> $ python --version
> Python 3.10.13
> ```

Is the ```env +foo``` or specifying it in the pkgx.yaml just adding it to environment and leaving the version installed for dependency that poetry asks for?

**Comment by jhheider** [comment]
`env +foo` adds it to the currently active environment, if a suitable version can be resolved against the existing constraints. poetry lists:
```yaml
dependencies:
  python.org: '>=3<3.12'
```
so, `env +python^2` or `env +python\>3.13` will fail, if poetry is loaded in the environment.

**Comment by j1philli** [comment]
Okay so it doesn't make both version available. Thanks

**Comment by mxcl** [comment]
> Okay so it doesn't make both version available. Thanks

We possibly should allow this, it doesn’t exactly hurt. But needs thought. Currently deps can only be resolved to a single version in a constraint graph.

> I believe we treat @ as `~`

`@` is complex.

* `@3` → `^3`
* `@3.1` → `~3`
* `@3.1.2 → `>=3.1.2<3.1.3`
* `@3.1.2.3 → `>=3.1.2.3<3.1.3.4`
* etc.

I think this is in the docs.

**Comment by j1philli** [comment]
> We possibly should allow this, it doesn’t exactly hurt. But needs thought. Currently deps can only be resolved to a single version in a constraint graph.

No Python only wants one in an environment at a time. I was just confirming that it wasn't adding both.

**Comment by mxcl** [comment]
however you can install multiple pythons alongside each other. I wonder if because that is true we should allow environments with multiple pythons? Food for thought.

**Comment by jhheider** [comment]
> however you can install multiple pythons alongside each other. I wonder if because that is true we should allow environments with multiple pythons? Food for thought.

i vote "one environment should use a unified python (or call `pkgx +python@version python foo` for esoteric needs)."

**Comment by j1philli** [comment]
@jhheider is right

**Comment by mxcl** [comment]
Yeah that sounds super `pkgx`ish.
