### ISSUE TITLE
Will pkgx support fetching resources through a proxy?

### ISSUE THREAD

**Issue by jhthorsen** [pkgxdev/pkgx#811]
I got HTTPS_PROXY, https_proxy, HTTP_PROXY and http_proxy set in my shell, but I get:

> fatal: unable to access 'https://github.com/pkgxdev/pantry/': Failed to connect to github.com port 443: Connection timed out

Is this something that can/will be supported?

curl, git and other commands work as expected.

**Comment by mxcl** [comment]
k… deno already claims to automatically support these https://docs.deno.com/runtime/manual/basics/modules/proxies

we use `fetch` for downloads.

**Comment by mxcl** [comment]
any suggestions on how I can test this locally?
