### ISSUE TITLE
Document `pkgx --sync`

### ISSUE THREAD

**Issue by svenjacobs** [pkgxdev/pkgx#813]
`pkgx --sync` is currently a hidden gem that helps when the pantry doesn't update automatically for some reason.
Unfortunately that command is not documented anywhere.

**Comment by mxcl** [comment]
> for some reason

I'll fix the bug. While I understand that it is frustrating that this isn't documented, I in general believe that documenting small details can make a tool harder to use.

I'll add it to an FAQ.

**Comment by mxcl** [comment]
I notice it is in the verbose help: `pkgx --verbose --help`. I agree this is hidden, but well, it is somewhere. Still adding to the FAQ.
