### ISSUE TITLE
Legacy symlink to package in `/usr/local/bin` fails install of that package

### ISSUE THREAD

**Issue by vladdeSV** [pkgxdev/pkgx#814]
I had a legacy symlink to `node` in my `/usr/local/bin`.

When I ran `pkgx install node` I got this error:

```
pkgx: no programs provided by pkgs
```

Removing the symlink fixed the error problem. However, the error message was very confusing, as it doesn't really seem to relate to the problem.

**Comment by mxcl** [comment]
wut. weird. having a look
