### ISSUE TITLE
`pkgx` / `dev` does not always recognize environment when jumping into subdirectories

### ISSUE THREAD

**Issue by svenjacobs** [pkgxdev/pkgx#836]
I noticed that `pkgx` / `dev` does not always recognize the current environment when jumping into subdirectories.
This is the contents of my monorepo `firebase`:

```
- Developer
  - firebase
    - firebase
    - firebase-common
    - pkgx.yaml
```

```
# Starting in "Developer"
❯ cd firebase
env +nodejs.org^18 +google.com/firebase-tools +git-scm.org
❯ cd ..
env -nodejs.org^18 -google.com/firebase-tools -git-scm.org
❯ cd firebase/firebase
× no env
❯ cd ..
env +nodejs.org^18 +google.com/firebase-tools +git-scm.org
❯ cd ..
env -nodejs.org^18 -google.com/firebase-tools -git-scm.org
❯ cd firebase/firebase-common
env +nodejs.org^18 +google.com/firebase-tools +git-scm.org
```

Notice how it does not pick up the environment when jumping straight into `firebase/firebase`. I don't know what's so special about this directory and I was not able to reproduce this with sample directories with the same setup.

pkgx `1.1.0`
zsh `5.9`

**Comment by svenjacobs** [comment]
Nevermind, it seems the contents of `$HOME/Library/Application Support/pkgx/dev` was in an invalid state. It contained `firebase/dev.pkgx.activated` and  `firebase/firebase/dev.pkgx.activated`. I don't know how this could have happened, maybe when I was trying out `pkgx` and `dev`. I deleted the contents of the dir `dev` and run the `dev` command again in the root `firebase` directory and now everything works as expected.

**Comment by mxcl** [comment]
We should probs try to help the user out in such scenarios with good warnings. Nothing immediately comes to mind for how to do this though.
