### ISSUE TITLE
PATH env var in pkgx.yaml breaking $PATH

### ISSUE THREAD

**Issue by sporkd** [pkgxdev/pkgx#841]
Defining a PATH env var in `pkgx.yaml` causes all other pkgx entries to be lost from my $PATH. Best way to illustrate is with two sessions:

### First when a `PATH` env var is defined
<img width="835" alt="Screenshot 2023-10-27 at 4 09 58 PM" src="https://github.com/pkgxdev/pkgx/assets/11115/44cc0f4d-2c4a-475f-9720-70ccbbbd0cbe">

Yarn is not in my path until I run `env` to reload it.

### But commenting out the `PATH` env var fixes the problem
<img width="711" alt="Screenshot 2023-10-27 at 4 07 31 PM" src="https://github.com/pkgxdev/pkgx/assets/11115/46d54bc8-1f59-47ff-993b-46097e100d59">

Now yarn is in my path without reloading the env 👍

**Comment by mxcl** [comment]
hmm sorry, I'm surprised it doesn't work. Will fix.

**Comment by sporkd** [comment]
No need to apologize @mxcl😃. Just trying to help out by documenting things.

**Comment by mxcl** [comment]
So I plan to fix this today by only accepting `${FOO}` or `$FOO`. I don’t know a shell that this doesn’t work for, but if in future there are shells it doesn’t we can convert those syntaxes.

Then if other ideas for what can be supported emerge we can whitelist them.

IMO if you want more power than that you use something like direnv.

**Comment by mxcl** [comment]
my bad managed to mix this one up with #842
