### ISSUE TITLE
cannot run python projects that use poetry 

### ISSUE THREAD

**Issue by twilwa** [pkgxdev/pkgx#846]
![image](https://github.com/pkgxdev/pkgx/assets/111034762/ce4d3f0c-e36d-4c90-999f-3dc57a7ed278)
running the poetry install script i end up with two instances of poetry, i can pkgx poetry install, but i can't pkgx install poetry
am tired but will try to give more info in am

**Comment by jhheider** [comment]
```shell
$ pkgx install poetry
pkgx: installed: ~/.local/bin/poetry
```

possibly we're assuming your ~/.local/bin exists? if you `mkdir -p ~/.local/bin` does the install succeed?

**Comment by mxcl** [comment]
if so then it's a dumb bug and I'm sorry

**Comment by mxcl** [comment]
hmm we definitely `mkdir` first. What `pkgx --version` is this?

**Comment by mxcl** [comment]
I can't see how this can’t work We create the directory on every path.

Assuming it was an old pkgx version and this is fixed. Reopen if not fixed. Thanks for the report.
