### ISSUE TITLE
parse issue github.com/axllent/mailpit

### ISSUE THREAD

**Issue by kishaningithub** [pkgxdev/pkgx#855]
When i ran the command `env +ruff` the following issue occurred

```bash
$ env +ruff
× parse error github.com/axllent/mailpit
│ this is a serious issue. please report the bug
╰─➤ https://github.com/pkgxdev/pkgx/issues/new?title=parse+issue+github.com/axllent/mailpit
```

## pkgx version

```bash
$ pkgx --version
pkgx 1.1.0
```

**Comment by jhheider** [comment]
hm. `pkgx +ruff` and `pkgx +mailpit` both work for me. try `pkgx --sync` in case you got a bad pull of the pantry. if that doesn't fix it, you might have a bad version of the package.yml for mailpit in your PKGX_PANTRY_PATH or local pantry checkout.

**Comment by kishaningithub** [comment]
After i did `env +ruff@latest` it magically started working again.

**Comment by mxcl** [comment]
ah, dang. Would have liked to have caught this, it must have been corruption in the yaml and I would have liked to have seen it.

`@latest` can trigger a silent `--sync` so probs was that.
