### ISSUE TITLE
Document modes [pkgx install/uninstall/etc]

### ISSUE THREAD

**Issue by krzyzanowskim** [pkgxdev/pkgx#860]
As of today, the `pkgx --help --verbose` does not mention any of the "mode" like `install`, which is then used in documentation. It would be helpful to have documented commands.

The usage would become:

`pkgx [mode] [+pkg~x.y…] [program|path] [--] [arg…]`

and follow with a section about mode/commands

**Comment by mxcl** [comment]
Perhaps. I consider `--help` to be a “wtf is this” output. The last line does direct the user to the full documentation which includes all possible usages.

**Comment by krzyzanowskim** [comment]
thank you!

**Comment by mxcl** [comment]
Thank you! Was a valid point. Now we are better overall because of your suggestion.
