### ISSUE TITLE
shell prompt get slow after `dev`

### ISSUE THREAD

**Issue by MarkusZoppelt** [pkgxdev/pkgx#867]
When activating `dev` in a development directory, my shell prompt gets slow (taking ~1sec after pressing `<Enter>`).

@mxcl suspects "the command not found handler" is probably being triggered.

I'm on macOS, shell is zsh, Terminal is Wezterm
Here's my zshrc:
https://github.com/MarkusZoppelt/dotfiles/blob/main/.zshrc

**Comment by MarkusZoppelt** [comment]
Fixed after `rm -rf ~/.pkgx/git-scm.org`

**Comment by jhheider** [comment]
sweet. then it was the fixes we've already incorporated.
