### ISSUE TITLE
after attempting to uninstall pkgx, it now attempts to manage my Ubuntu install

### ISSUE THREAD

**Issue by twilwa** [pkgxdev/pkgx#872]
![image](https://github.com/pkgxdev/pkgx/assets/111034762/dba23e79-2524-4c03-b186-22e0575883ee)
![image](https://github.com/pkgxdev/pkgx/assets/111034762/f154444d-0c7b-4436-b9e2-c1627d5ece7c)
followed the steps there from within my wsl install, can't uninstall pkgx and i think it's trying to handle my Ubuntu via package graphs, heh.

**Comment by jhheider** [comment]
if you ran `pkgx integrate` you'll want to remove the line from your .bashrc or .zshrc and restart your shell.

**Comment by mxcl** [comment]
You didn't uninstall pkgx: `rm /usr/local/bin/pkgx` so I'd recommend:

```sh
pkgx deintegrate
rm /usr/local/bin/pkgx
# now start a new terminal session
```


Which uninstall instructions did you read that didn't make it clear you have to delete pkgx in order for it to be uninstalled?

**Comment by mxcl** [comment]
FYI we are not managing your ubuntu install or anything of the sort. You have the shell integration enabled and some part of your shell’s startup sequence is trying to run something with pkgx for some reason.

**Comment by mxcl** [comment]
k our uninstall instructions indeed failed to mention removing `/usr/local/bin/pkgx` 🤦🏻‍♂️
