### ISSUE TITLE
env doesn't trigger a refresh on not-found

### ISSUE THREAD

**Issue by sanchitram1** [pkgxdev/pkgx#877]
```sh
 $ env +gitql
we have not packaged that yet

 $ gitql
^^ type `x` to run that

 $ x
env +gitql && gitql 
 ✓  ~/.pkgx/libssh2.org/v1.11.0
 ✓  ~/.pkgx/libgit2.org/v1.7.1
 ✓  ~/.pkgx/amrdeveloper.github.io/GQL/v0.9.0
error: the following required arguments were not provided: 
  --repos <REPOS>...

Usage: gitql --repos <REPOS>...

For more information, try '--help'.
```

First error is the issue.  Second error is expected.  When trying to load `gitql`, which was just packaged, I assumed `env +gitql` would do the trick, but I kept getting a package not found error.

**Comment by michaelessiet** [comment]
Running `pkgx --sync` would've fixed this. It would ensure that your pantry is synced up with the one in the server. But I think this has been fixed now
