### ISSUE TITLE
pkgx uninstall does not work

### ISSUE THREAD

**Issue by char8x** [pkgxdev/pkgx#881]
### Output

When executing uninstall, node cli is executed instead.

```sh
❯ pkgx uninstall node
Welcome to Node.js v18.19.0.
Type ".help" for more information.
>
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
>
```

### Env

```sh
❯ pkgx --version
pkgx 1.1.1

❯ cat ~/.local/bin/node
#!/bin/sh
exec pkgx +nodejs.org^18 -- node "$@"
```

**Comment by mxcl** [comment]
Did you per chance `pkgx install node` before we had an uninstall command? I bet if you delete `~/.local/bin/node` and reinstall then uninstall will work.

Apologies if that is the case. 1.0.0 didn't support uninstall.

If that isn’t the issue can you `cat ~/.local/bin/node` for me?

**Comment by char8x** [comment]
> Did you per chance `pkgx install node` before we had an uninstall command? I bet if you delete `~/.local/bin/node` and reinstall then uninstall will work.

Yes, delete and reinstall then uninstall works, thanks !
