### ISSUE TITLE
enable `dev cdk` when cdk.json is present 

### ISSUE THREAD

**Issue by dburriss** [pkgxdev/pkgx#883]
Running `cdk` requires a *cdk.json* file. When running `dev` when this file is present, I expect cdk to be enabled for the env, since `cdk` is a known tool to pkgx.

**Comment by dburriss** [comment]
I did some digging and do I understand correctly that if I submitted a PR to [devenv.ts](https://github.com/pkgxdev/pkgx/blob/main/src/utils/devenv.ts#L24) updating the case to look for cdk.json, this should work?

**Comment by jhheider** [comment]
yep, that's the recommended path!

**Comment by michaelessiet** [comment]
Is it safe to close this?

**Comment by michaelessiet** [comment]
@dburriss have you made a PR?

**Comment by dburriss** [comment]
@michaelessiet I did but there are some questions on it around treating
