### ISSUE TITLE
attempting to run pkgx on iShell i686 32-bit architecture on iOS

### ISSUE THREAD

**Issue by mfts** [pkgxdev/pkgx#886]
I tried installing pkgx on iShell a linux emulator for iOS. It runs i686 according to `uname -m` but i tried installing the x86_64 version of pkgx anyways. 

It seems like everything is in place and downloaded correctly. But the file cannot be read properly

![image](https://github.com/pkgxdev/pkgx/assets/4049052/49471aa7-0dd4-4bab-be72-b9bbe6f081bf)

iShell uses Alpine linux

**Comment by mxcl** [comment]
Added to platform support megaticket
