### ISSUE TITLE
When will the "pkg integrate" works for fish shell

### ISSUE THREAD

**Issue by Shobhit0109** [pkgxdev/pkgx#965]
Please add support for fish shell

**Comment by Shobhit0109** [comment]
When i tried this i got this error
![image](https://github.com/pkgxdev/pkgx/assets/97778494/0f874c8c-628d-42a2-97c5-10e8aa481e65)

then i also try the suggested but it isn't working on fish
![image](https://github.com/pkgxdev/pkgx/assets/97778494/8f15f369-6195-4041-bef7-599e62341013)

**Comment by mxcl** [comment]
Dupes #845
