### ISSUE TITLE
Pkgx downloaded the wrong version of Go into the right folder

### ISSUE THREAD

**Issue by fredrikaverpil** [pkgxdev/pkgx#983]
I've defined a project to use go 1.21 via `pkgx.yaml`, but pkgx still uses go 1.22.

```bash
❯ pkgx --version
pkgx 1.1.6

❯ go version
^^ type `x` to run that

❯ cat myproj/pkgx.yaml
dependencies:
  - go@1.21

❯ cd myproj
env +go.dev~1.21 +git-scm.org

❯ go version
go version go1.22.1 darwin/arm64

❯ which go
/Users/fredrik/.pkgx/go.dev/v1.21.8/bin/go
```

I ran `rm -rf /Users/fredrik/.pkgx/go.dev` and re-downloaded it all, but it ended up doing the same thing.
I also tried adding a patch version in `pkgx.yaml`:

```bash
❯ cat myproj/pkgx.yaml
dependencies:
  - go@1.21.5

❯ cd myproj
 ✓  ~/.pkgx/go.dev/v1.21.5
env +go.dev@1.21.5 +git-scm.org

❯ go version
go version go1.22.1 darwin/arm64

❯ which go
/Users/fredrik/.pkgx/go.dev/v1.21.5/bin/go
```

My starship prompt also shows the 1.22 version no matter what:

```bash
book-service on  master [$] via  v1.22.1
```

Furthermore;

```bash
❯ ll ~/.pkgx/go.dev
Permissions Size User    Group Date Modified Name
lrwxr-xr-x     - fredrik staff  7 Mar 17:01  v* -> v1.22.1
lrwxr-xr-x     - fredrik staff  7 Mar 17:01  v1 -> v1.22.1
lrwxr-xr-x     - fredrik staff  7 Mar 16:57  v1.21 -> v1.21.8
drwxr-xr-x     - fredrik staff  7 Mar 17:08  v1.21.5
drwxr-xr-x     - fredrik staff  7 Mar 16:57  v1.21.8
lrwxr-xr-x     - fredrik staff  7 M
```

What could be wrong?

**Comment by fredrikaverpil** [comment]
Hey @michaelessiet, I just did this;

```bash
brew uninstall pkgx
rm -rf ~/.pkgx
rm -rf "${XDG_CACHE_HOME:-$HOME/Library/Caches}/pkgx"
rm -rf "${XDG_DATA_HOME:-$HOME/Library/Application Support}"/pkgx
```

The problem still persists and it's driving me nuts at this point;

```bash
❯ brew install pkgx
...

❯ pkgx go@1.21 version
 ✓  ~/.pkgx/curl.se/ca-certs/v2023.12.12
 ✓  ~/.pkgx/openssl.org/v1.1.1w
 ✓  ~/.pkgx/go.dev/v1.21.8
go version go1.21.8 darwin/arm64           <--- 👍

❯ ll ~/.pkgx/go.dev
Permissions Size User    Group Date Modified Name
lrwxr-xr-x@    - fredrik staff  7 Mar 17:35  v* -> v1.21.8
lrwxr-xr-x@    - fredrik staff  7 Mar 17:35  v1 -> v1.21.8
lrwxr-xr-x@    - fredrik staff  7 Mar 17:35  v1.21 -> v1.21.8
drwxr-xr-x@    - fredrik staff  7 Mar 17:35  v1.21.8


❯ cd myproj
❯ pkgx go@1.21 version
go version go1.22.1 darwin/arm64           <--- 🤯
```

**Comment by fredrikaverpil** [comment]
Problem solved, in the project's `go.mod` I apparently had `toolchain go1.22.1` which apparently causes go itself to download a new version (which I already had cached).

This was such a mindfuck. Sorry for the noise.

**Comment by jhheider** [comment]
in general, i like how good modern languages (specifically `go` and `rust`) are at managing themselves. but, once in a while, there's a very subtle foot-gun in the mix. this was a good find.

**Comment by mxcl** [comment]
I get why they do this, but really they should leave such stuff to tools like us. They are the wrong layer to do this sort of thing and by doing it they are adding complexity for everyone as well as burden for themselves to maintain.
